# .github/workflows/ci.yml
name: CI - Test and Lint

on:
  push:
    branches: ["main", "develop", "feature/*"]   # run on pushes to main, develop, or feature branches
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Lint code
        run: npm run lint   # runs the linter (e.g. ESLint) on the code

      - name: Run tests
        run: npm test       # runs the test suite
