name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH connection with password
        env:
          HOST_PASS: ${{ secrets.HOST_PASS }}
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
        run: |
          echo "Attempting SSH connection to $HOST_USER@$HOST_IP..."
          sshpass -p "$HOST_PASS" ssh \
            -o StrictHostKeyChecking=no \
            -o PreferredAuthentications=password \
            -o PubkeyAuthentication=no \
            -p $HOST_PORT "$HOST_USER@$HOST_IP" \
            "echo '✅ SSH connection successful!'"
